GET http://localhost:10101/api/products

###
GET http://localhost:10101/api/products?from=1&price_min=10&price_max=7000

###
GET http://localhost:10101/api/products/1

###
POST http://localhost:10101/api/products
Content-Type: application/json

{
  "name": "banana",
  "price": 6000,
  "image": "https://loremflickr.com/640/480",
  "categoryId": 1,
  "userId": 1,
  "description": "este producto es muy bueno"
}

###
PUT http://localhost:10101/api/products/9
Content-Type: application/json

{
  "name": "telefono"
}

###
DELETE http://localhost:10101/api/products/1
