GET http://localhost:10101/api/users?from=1

###
GET http://localhost:10101/api/users

###
POST http://localhost:10101/api/users
Content-Type: application/json

{
  "email": "maria2@gmail.com",
  "password": "123456",
  "image": "https://loremflickr.com/640/480",
  "roleId": "client"
}

###
PUT http://localhost:10101/api/users/1
Content-Type: application/json

{
  "email": "mariapaula@gmail.com",
  "password": "maria",
  "image": "https://maria.com/640/480",
  "role": "client"
}

###
DELETE http://localhost:10101/api/users/2
